apiVersion: v1
kind: ConfigMap
metadata:
  name: pw-cm
  namespace: pw
data:
  PW_PORT: '8080'
  PW_LOG_LEVEL: 'info'
  PW_MESSAGE_MAX_LENGTH: '4096'
  PW_ENCRYPTED_MESSAGE_MAX_LENGTH: '15000'
  PW_LOCALE_ID: 'en'
  PW_REDIS_URL: 'redis://pw-redis-svc:6379/'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pw
  namespace: pw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pw
  template:
    metadata:
      labels:
        app: pw
    spec:
      containers:
        - name: pw
          image: tinyops/pw:1.4.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: pw-cm
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: tz-config
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: pw-svc
  namespace: pw
spec:
  selector:
    app: pw
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pw-ingress
  namespace: pw
spec:
  ingressClassName: nginx
  rules:
    - host: pw.company.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pw-svc
                port:
                  number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pw-redis
  namespace: pw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pw-redis
  template:
    metadata:
      labels:
        app: pw-redis
    spec:
      containers:
        - name: pw-redis
          image: redis:7.4.0-alpine3.20
          args: ["redis-server", "--save", "", "--appendonly", "no", "--maxmemory", "128mb"]
---
apiVersion: v1
kind: Service
metadata:
  name: pw-redis-service
  namespace: pw
spec:
  selector:
    app: pw-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc-pw-claim
  namespace: pw
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-pw
  namespace: pw
  annotations:
    volume.beta.kubernetes.io/mount-options: vers=4,port=0,hard,proto=tcp,local_lock=none,async
spec:
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: pw
    name: nfs-pvc-pw-claim
  capacity:
    storage: 100MB
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.200
    path: /opt/pw/
