[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.44"

hex = "0.4.3"
rust-crypto = "0.2.36"
rand = "0.8.5"

log = "0.4.19"

[dev-dependencies]
env_logger = "0.9.3"
fake = "2.6.1"
