apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pw.fullname" . }}-redis
  labels:
    {{- include "pw.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      {{- include "pw.redisSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pw.redisSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pw.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.targetPort }}
              protocol: TCP
          {{- if .Values.redis.auth.enabled }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pw.redisSecretName" . }}
                  key: redis-password
          {{- end }}
          args:
            - redis-server
            - --save
            - {{ .Values.redis.config.save | quote }}
            - --appendonly
            - {{ .Values.redis.config.appendOnly | quote }}
            - --maxmemory
            - {{ .Values.redis.config.maxMemory | quote }}
            {{- if .Values.redis.auth.enabled }}
            - --requirepass
            - $(REDIS_PASSWORD)
            {{- end }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                {{- if .Values.redis.auth.enabled }}
                - -a
                - $(REDIS_PASSWORD)
                {{- end }}
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                {{- if .Values.redis.auth.enabled }}
                - -a
                - $(REDIS_PASSWORD)
                {{- end }}
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
