apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pw.fullname" . }}-pw
  labels:
    {{- include "pw.labels" . | nindent 4 }}
    app.kubernetes.io/component: pw
spec:
  replicas: {{ .Values.pw.replicaCount }}
  selector:
    matchLabels:
      {{- include "pw.pwSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pw.pwSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pw.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: pw
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.pw.image.repository }}:{{ .Values.pw.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pw.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.pw.service.targetPort }}
              protocol: TCP
          env:
            {{- if .Values.redis.auth.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pw.redisSecretName" . }}
                  key: redis-password
            - name: PW_REDIS_URL
              value: {{ printf "redis://:%s@%s:%d/" "$(REDIS_PASSWORD)" (include "pw.redisServiceName" .) (.Values.redis.service.port | int) | quote }}
            {{- else }}
            - name: PW_REDIS_URL
              value: {{ printf "redis://%s:%d/" (include "pw.redisServiceName" .) (.Values.redis.service.port | int) | quote }}
            {{- end }}
            {{- with .Values.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "pw.fullname" . }}-config
          livenessProbe:
            httpGet:
              path: /api/version
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/version
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.pw.resources | nindent 12 }}
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
              readOnly: true
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: tz-config
          hostPath:
            path: /etc/localtime
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.pw.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pw.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pw.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
