{{- if .Values.redis.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pw.redisSecretName" . }}
  labels:
    {{- include "pw.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  redis-password: {{ include "pw.redisPassword" . | b64enc | quote }}
{{- end }}
