[application]
name = "pw"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "PW"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]
index_on_404 = true

[web.resource]
style = ["bootstrap.min.css", "index.css"]

script = []

[web.resource.dev]
style = []
script = []